spring:
  redis:
    host: 127.0.0.1
    password: 19991125
    port: 6379
    timeout: 15000
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000
        min-idle: 10


