# 端口
server:
  port: 9000

# 应用名称
spring:
  application:
    name: gateway-service

  cloud:
    # 配置nacos服务发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # gateway可以通过服务注册中心获取对应的微服务
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1

        - id: push-service
          uri: lb://push-service
          predicates:
            - Path=/push/**
          filters:
            - StripPrefix=1

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1

        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay/**
          filters:
            - StripPrefix=1

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
