# 端口
server:
  port: 9000

# 应用名称
spring:
  application:
    name: gateway-service

  cloud:
    # 配置nacos服务发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # gateway可以通过服务注册中心获取对应的微服务
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 以下是认证中心的路由配置
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
        # 以下是业务模块的路由配置
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1

        - id: push-service
          uri: lb://push-service
          predicates:
            - Path=/push/**
          filters:
            - StripPrefix=1

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1

        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay/**
          filters:
            - StripPrefix=1

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
  # 对redis进行配置
  redis:
    host: 127.0.0.1
    password: 19991125
    port: 6379
    timeout: 15000
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000
        min-idle: 10

# 配置网关白名单，直接放行
oauth2:
  cloud:
    sys:
      parameter:
        ignoreUrls:
          - /oauth/**