# 端口
server:
  port: 9002

# 应用名称
spring:
  application:
    name: message-service

  cloud:
    # 配置nacos服务发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 配置sentinel负责流量控制、服务熔断
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8858
        # 冲突自加1
        port: 8719
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/focus?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 19991125
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    # 时区调整
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    password: 19991125
    port: 6379
    timeout: 15000
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000
        min-idle: 10
